### ISSUE TITLE
Parsing fails when using single quotes

### ISSUE THREAD

**Issue by tionis** [sogaiu/janet-xmlish#2]
The grammar fails when the XML uses single quotes (the following example is extracted from an e-book file):
```
<?xml version='1.0' encoding='utf-8'?>
<some>
  <xml>
    here
  </xml>
</some>
```

**Comment by sogaiu** [comment]
I attempted to address this in 23b0dae05783cac959c21022a0fcc712ad958d92

Please give it a try and let me know how it goes.

**Comment by tionis** [comment]
Looking good!
I just let it parse my 300 e-books, and it seems it read them all correctly.
Thanks for the fix! :+1:

**Comment by sogaiu** [comment]
@tionis Thanks for the report and testing!
